### ISSUE TITLE
Handle the output of responses and results

### ISSUE THREAD

**Issue by hscells** [hscells/iuserstudy#7]
There a lot of different things that should be output as participants progress:

 - user interaction data: mouse movements and button clicks. All buttons should be given a unique and easily identifiable ID that we can come back to later and see what things users clicked on. It would also be nice to be able to visualise this data somehow. This data should be output into a file called `logs/bb-query_vis_study.csv`

 - survey responses: the answers to the questions between tasks. Currently this is being stored in the bucket system. Can we write something that can easily export this data into something more manageable? Would be nice to be able to have some software to analyse and visualise this as well. I think this data is also being output into a folder in the root directory: `data/responses/`

 - query reformulation data: captured queries that have been formulated in both interfaces. I think this data is being output into a file in the root directory of searchrefiner called `data`. We need to check to see if the data is indeed being output correctly, and to document how the data is being output so we can come back to it later.

**Comment by hanglics** [comment]
add ids to every important element in the pages.

**Comment by hanglics** [comment]
added unique ids to `pubmed.html`, `queryvis.html`, `index.html` and `forms.tmpl.html`.

**Comment by hanglics** [comment]
fixed the first issue in here, other two moved to #13
